[theme]

# Primary accent for interactive elements
primaryColor = '#f08e32'

# Background color for the main content area
backgroundColor = '#1f036b'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3ce6b5'

# Color used for almost all text
textColor = '#f0e6ce'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"